QUESTION 1:

In [1]:
import numpy as np
ar = np.arange(2,51,3)
print(ar)


[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


QUESTION 2:

In [2]:

import numpy as np
a1=[] 
a2=[]
for i in range(0, 5): 
    ele = int(input())
    a1.append(ele)
for i in range(0, 5): 
    ele = int(input())
    a2.append(ele) 
a1 = np.array(a1)
a2 = np.array(a2)
print(np.concatenate((a1,a2)))
print(np.sort(np.concatenate((a1,a2))))

1
5
1
6
7
3
2
0
5
7
[1 5 1 6 7 3 2 0 5 7]
[0 1 1 2 3 5 5 6 7 7]


QUESTION 3:

In [3]:
import numpy as np
arr = np.array([[1,2,3],[1,3,5],[1,3,4]])
print(arr.ndim)
print(arr.size)

2
9


QUESTION 4:

In [4]:
import numpy as np
arr=np.random.rand(5,)
print(arr.ndim)
nw_arr = arr[np.newaxis, :]
print(nw_arr.ndim)

1
2


QUESTION 5:

In [5]:
import numpy as np
arr1=np.random.rand(3,3)
arr2=np.random.rand(3,3)
print(np.vstack((arr1,arr2)))
print() 
print(np.hstack((arr1,arr2)))

[[0.22068245 0.56689436 0.91574106]
 [0.42250408 0.0699314  0.05400459]
 [0.76012471 0.95852425 0.43337018]
 [0.11085884 0.18052542 0.22240354]
 [0.94309142 0.25288361 0.19906112]
 [0.42511351 0.57388358 0.04708972]]

[[0.22068245 0.56689436 0.91574106 0.11085884 0.18052542 0.22240354]
 [0.42250408 0.0699314  0.05400459 0.94309142 0.25288361 0.19906112]
 [0.76012471 0.95852425 0.43337018 0.42511351 0.57388358 0.04708972]]


QUESTION 6:

In [6]:
import numpy as np
arr = np.array([1,9,3,1,5,2,5,6,4,3,9,7,6,8,9,2,6,7,8])
print(np.unique(arr,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 2, 2, 1, 2, 3, 2, 2, 3], dtype=int64))
